### ISSUE TITLE
TK11 - Integrar Pesos del Modelo en la Aplicación

### ISSUE THREAD

**Issue by marumunoz02** [ClaudiaMetz/Ponele-Musica-a-tus-Emociones-_-Grupo10-_-ISPC-_-TSCDIA#11]
Integrar los pesos del modelo entrenado para que el modelo realice predicciones precisas.

**Comment by kelo72** [comment]
Inicio de tareas

**Comment by kelo72** [comment]
se agregaron los pesos ya guardados
