### ISSUE TITLE
TK04 - crear Modelo en Colab

### ISSUE THREAD

**Issue by horacioequiroga** [ClaudiaMetz/Ponele-Musica-a-tus-Emociones-_-Grupo10-_-ISPC-_-TSCDIA#4]
TK04 - Crear Modelo en Colab

**Comment by jona-bustos** [comment]
Buenas noches a todos.
Comparto colab con Modelos:
1- Colab Modelo Final: https://colab.research.google.com/drive/12faMWJeMDSSs2MvHXCcXVDVJEoanG5j_?usp=drive_link
2- Colab para Historias: https://colab.research.google.com/drive/1gB36APaIzgCofe1jEBVFun4BtVVmHuyq?usp=drive_link
Resta ver con Kelo como imprimir todas las páginas y agregar la parte de la música.
Saludos!!
